export type RequirementStatus =
  | 'Required'
  | 'Conditional'
  | 'Optional'
  | 'System Generated'

export type RequirementSection =
  | 'personal'
  | 'business'
  | 'financial'
  | 'technology'
  | 'verification'
  | 'commercial'

export type MarketplacePurpose =
  | 'buy'
  | 'sell'
  | 'license'
  | 'partner'
  | 'explore'
  | 'commercialize'

export interface MarketplaceRequirement {
  id: string
  section: RequirementSection
  title: string
  description: string
  status: RequirementStatus
  appliesTo: MarketplacePurpose[]
}

export const marketplaceRequirements: MarketplaceRequirement[] = [
  {
    id: 'personal-profile',
    section: 'personal',
    title: 'Personal Profile',
    description:
      'Basic identity and contact information used to establish your Tech FounDX participant profile.',
    status: 'Required',
    appliesTo: ['buy', 'sell', 'license', 'partner', 'explore', 'commercialize'],
  },
  {
    id: 'business-profile',
    section: 'business',
    title: 'Business / Organization Profile',
    description:
      'Business identity, activity, experience and organizational information where relevant to your marketplace purpose.',
    status: 'Conditional',
    appliesTo: ['buy', 'sell', 'license', 'partner', 'commercialize'],
  },
  {
    id: 'financial-profile',
    section: 'financial',
    title: 'Financial / Investment Profile',
    description:
      'Budget, investment capability and related commercial information only when required by the selected activity or transaction.',
    status: 'Conditional',
    appliesTo: ['buy', 'sell', 'license', 'partner', 'commercialize'],
  },
  {
    id: 'technology-profile',
    section: 'technology',
    title: 'Technology / Project Profile',
    description:
      'Technology, machinery, product, system, project or solution information relevant to the marketplace activity.',
    status: 'Conditional',
    appliesTo: ['sell', 'license', 'commercialize', 'partner'],
  },
  {
    id: 'buyer-requirements',
    section: 'technology',
    title: 'Technology Requirement',
    description:
      'The technology, capability, industry, application and technical outcome you are looking for.',
    status: 'Conditional',
    appliesTo: ['buy'],
  },
  {
    id: 'ownership-ip',
    section: 'verification',
    title: 'Ownership / Intellectual Property',
    description:
      'Ownership, IP rights, patents, licensing rights and relevant third-party component information where applicable.',
    status: 'Conditional',
    appliesTo: ['sell', 'license', 'commercialize'],
  },
  {
    id: 'verification-profile',
    section: 'verification',
    title: 'Verification Profile',
    description:
      'Identity, business, technology, ownership or financial evidence may be requested according to activity and verification requirements.',
    status: 'Conditional',
    appliesTo: ['buy', 'sell', 'license', 'partner', 'commercialize'],
  },
  {
    id: 'commercial-profile',
    section: 'commercial',
    title: 'Commercial / Transaction Requirements',
    description:
      'Commercial objective, transaction type, territory, licensing, partnership and related requirements when an activity progresses toward a transaction.',
    status: 'Conditional',
    appliesTo: ['buy', 'sell', 'license', 'partner', 'commercialize'],
  },
  {
    id: 'system-record',
    section: 'verification',
    title: 'System Records',
    description:
      'Account status, submission identifiers, timestamps, requirement progress and review status are generated by the marketplace system.',
    status: 'System Generated',
    appliesTo: ['buy', 'sell', 'license', 'partner', 'explore', 'commercialize'],
  },
]

export const purposeLabels: Record<MarketplacePurpose, string> = {
  buy: 'Buy Technology',
  sell: 'Sell Technology',
  license: 'License Technology',
  partner: 'Find a Technology Partner',
  explore: 'Explore Technologies',
  commercialize: 'Commercialize / Collaborate',
}
